# Generated by Django 3.0.3 on 2020-07-16 17:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlendName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_blend', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='KomposisiBean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pembuatan_komposisi', models.DateField(default=datetime.date(2020, 7, 17))),
                ('kode_komposisi', models.CharField(default='-', max_length=10)),
                ('komposisi_blend', models.CharField(max_length=50)),
                ('catatan', models.CharField(default='-', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionSampleBlend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_blend', models.CharField(max_length=100)),
                ('tanggal_pembuatan_sample', models.DateField(auto_now_add=True)),
                ('roast_date', models.DateField()),
                ('production_date', models.DateField()),
                ('penerima', models.CharField(default='-', max_length=10)),
                ('penerimaan_qc', models.BooleanField(default=False)),
                ('catatan', models.CharField(default='-', max_length=200)),
                ('kode_sample', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QCSampleBlend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_diterima', models.DateField()),
                ('catatan', models.CharField(default='-', max_length=150)),
                ('qc_acceptance', models.BooleanField(default=False)),
                ('blend_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.BlendName')),
                ('sample_blend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.ProductionSampleBlend')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionDiv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_blend', models.DateField()),
                ('nomor_set', models.PositiveIntegerField(max_length=50)),
                ('mesin', multiselectfield.db.fields.MultiSelectField(choices=[('froco-15', 'froco-15'), ('froco-25', 'froco-25')], max_length=17)),
                ('blend_code', models.CharField(max_length=50)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, max_length=50)),
                ('agtron_meter', models.PositiveIntegerField(default=0, max_length=50)),
                ('production_check_pass', models.BooleanField(default=False)),
                ('cupping', models.BooleanField(default=False)),
                ('qc_check_pass', models.BooleanField(default=False)),
                ('taste_notes', models.CharField(default='-', max_length=100)),
                ('pack_status', models.BooleanField(default=False)),
                ('product_code', models.SlugField(allow_unicode=True)),
                ('jenis_blend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.BlendName')),
                ('komposisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.KomposisiBean')),
            ],
        ),
    ]
