# Generated by Django 3.0.8 on 2020-08-03 03:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlendName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_blend', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BlendReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_date', models.DateField()),
                ('machine', multiselectfield.db.fields.MultiSelectField(choices=[('a', 'fr15'), ('b', 'fr25'), ('c', 'fr15-25')], max_length=5)),
                ('shift', multiselectfield.db.fields.MultiSelectField(choices=[('a', 'pagi'), ('b', 'siang')], max_length=3)),
                ('catatan_laporan', models.TextField(default='-', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='DaftarCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_customer', models.CharField(max_length=20)),
                ('no_telp', models.CharField(max_length=20)),
                ('alamat', models.CharField(max_length=30)),
                ('pic', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Karyawan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_panggilan', models.CharField(max_length=20)),
                ('nama_lengkap', models.CharField(max_length=20)),
                ('no_telp', models.CharField(max_length=20)),
                ('alamat', models.CharField(max_length=100)),
                ('status_aktif', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'STAFF',
                'verbose_name_plural': 'STAFF',
            },
        ),
        migrations.CreateModel(
            name='KomposisiBean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pembuatan_komposisi', models.DateField(default=datetime.date(2020, 8, 3))),
                ('kode_komposisi', models.CharField(default='-', max_length=10)),
                ('komposisi_blend', models.CharField(max_length=50)),
                ('catatan', models.CharField(default='-', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_name', models.CharField(max_length=20)),
                ('pack_volume', models.DecimalField(decimal_places=2, max_digits=9)),
                ('pack_uom', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionSampleBlend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_blend', models.CharField(max_length=100)),
                ('tanggal_pembuatan_sample', models.DateField(auto_now_add=True)),
                ('roast_date', models.DateField()),
                ('production_date', models.DateField()),
                ('mesin', models.CharField(choices=[('fr15', 'fr15'), ('fr25', 'fr25')], default='', max_length=50)),
                ('penerima', models.CharField(default='-', max_length=10)),
                ('diterima_qc', models.BooleanField(default=False)),
                ('catatan', models.CharField(default='-', max_length=200)),
                ('kode_sample', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RunTimeStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blend_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.BlendName')),
                ('pack_size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.Pack')),
            ],
        ),
        migrations.CreateModel(
            name='QCSampleBlend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_diterima', models.DateField()),
                ('catatan', models.CharField(default='-', max_length=150)),
                ('qc_acceptance', models.BooleanField(default=False)),
                ('blend_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.BlendName')),
                ('sample_blend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.ProductionSampleBlend')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionDiv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roast_date', models.DateField(default=datetime.date(2020, 8, 3))),
                ('nomor_set', models.PositiveIntegerField(max_length=50)),
                ('mesin', multiselectfield.db.fields.MultiSelectField(choices=[('fr15', 'fr15'), ('fr25', 'fr25')], max_length=9)),
                ('shift', models.CharField(choices=[('Pagi', 'Pagi'), ('Siang', 'Siang')], default='', max_length=60)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('agtron_meter', models.DecimalField(decimal_places=2, max_digits=4)),
                ('production_check_pass', models.BooleanField(default=False)),
                ('cupping', models.BooleanField(default=False)),
                ('qc_check_pass', models.BooleanField(default=False)),
                ('taste_notes', models.CharField(default='-', max_length=100)),
                ('pack_status', models.BooleanField(default=False)),
                ('initial_create', models.DateTimeField(auto_now_add=True)),
                ('komposisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.KomposisiBean')),
                ('pack_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='production.Pack')),
                ('production_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.BlendReport')),
            ],
            options={
                'verbose_name': 'Blend & Packing',
                'verbose_name_plural': 'Blend & Packing',
            },
        ),
        migrations.CreateModel(
            name='PackFormInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_dan_jam', models.DateTimeField(default=datetime.datetime(2020, 8, 3, 3, 15, 9, 219025, tzinfo=utc))),
                ('volume_pack', models.DecimalField(decimal_places=2, max_digits=9)),
                ('volume_quantity', models.DecimalField(decimal_places=2, max_digits=9)),
                ('catatan', models.TextField(default='-', max_length=200)),
                ('blend_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.RunTimeStock')),
                ('jenis_pack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.Pack')),
            ],
            options={
                'verbose_name': 'Finish Good Input',
                'verbose_name_plural': 'Finish Good Input',
            },
        ),
        migrations.AddField(
            model_name='blendreport',
            name='blend_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.RunTimeStock'),
        ),
        migrations.AddField(
            model_name='blendreport',
            name='input_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.Karyawan'),
        ),
        migrations.AddField(
            model_name='blendreport',
            name='pack_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.Pack'),
        ),
        migrations.CreateModel(
            name='BarangKeluar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_dan_jam', models.DateTimeField(default=datetime.datetime(2020, 8, 3, 3, 15, 9, 219025, tzinfo=utc))),
                ('invoice_number', models.CharField(default='-', max_length=20)),
                ('volume_pack', models.DecimalField(decimal_places=2, max_digits=9)),
                ('volume_quantity', models.DecimalField(decimal_places=2, max_digits=9)),
                ('catatan', models.TextField(default='-', max_length=200)),
                ('blend_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.RunTimeStock')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.DaftarCustomer')),
                ('jenis_pack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.Pack')),
            ],
            options={
                'verbose_name': 'Barang Keluar',
                'verbose_name_plural': 'Barang Keluar',
            },
        ),
    ]
