# Generated by Django 3.0.8 on 2020-08-30 04:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisposalReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_BAP', models.DateField()),
                ('author', models.CharField(max_length=20)),
                ('diketahui_oleh', models.CharField(max_length=30)),
                ('hard_copy_url', models.URLField(default='')),
                ('note', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Kejadian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField()),
                ('reporter', models.CharField(default='-', max_length=15)),
                ('kronologi', models.TextField(max_length=300)),
                ('resolusi', models.TextField(max_length=300)),
            ],
            options={
                'verbose_name': 'Kejadian',
                'verbose_name_plural': 'Kejadian',
            },
        ),
        migrations.AlterField(
            model_name='barangkeluar',
            name='tanggal_dan_jam',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 30, 4, 56, 49, 603005, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='komposisibean',
            name='tanggal_pembuatan_komposisi',
            field=models.DateField(default=datetime.date(2020, 8, 30)),
        ),
        migrations.AlterField(
            model_name='packforminput',
            name='tanggal_dan_jam',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 30, 4, 56, 49, 603005, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='productiondiv',
            name='roast_date',
            field=models.DateField(default=datetime.date(2020, 8, 30)),
        ),
        migrations.CreateModel(
            name='DisposalItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_date', models.DateField()),
                ('material_name', models.CharField(max_length=50)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('value_per_kg', models.PositiveIntegerField(default=0, max_length=9)),
                ('note', models.TextField(max_length=300)),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.DisposalReport')),
            ],
        ),
    ]
