# Generated by Django 3.0.8 on 2020-07-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='pack_volume',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
