# Generated by Django 3.0.8 on 2020-07-27 09:47

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_auto_20200726_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='blendreport',
            name='machine',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('a', 'fr15'), ('b', 'fr25'), ('c', 'fr15-25')], default='a', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blendreport',
            name='shift',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('a', 'pagi'), ('b', 'siang')], default='a', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='komposisibean',
            name='tanggal_pembuatan_komposisi',
            field=models.DateField(default=datetime.date(2020, 7, 27)),
        ),
        migrations.AlterField(
            model_name='productiondiv',
            name='roast_date',
            field=models.DateField(default=datetime.date(2020, 7, 27)),
        ),
    ]
