# Generated by Django 3.0.8 on 2020-09-12 06:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_12sep20'),
        ('production', '0002_auto_20200830_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='productiondiv',
            name='production_process',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productiondiv',
            name='roasted_material',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='products.Roaster'),
        ),
        migrations.AlterField(
            model_name='barangkeluar',
            name='tanggal_dan_jam',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 12, 6, 29, 49, 170205, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='komposisibean',
            name='tanggal_pembuatan_komposisi',
            field=models.DateField(default=datetime.date(2020, 9, 12)),
        ),
        migrations.AlterField(
            model_name='packforminput',
            name='tanggal_dan_jam',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 12, 6, 29, 49, 170205, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='productiondiv',
            name='roast_date',
            field=models.DateField(default=datetime.date(2020, 9, 12)),
        ),
    ]
