# Generated by Django 3.0.3 on 2020-07-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_productionsampleblend_mesin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productionsampleblend',
            old_name='penerimaan_qc',
            new_name='diterima_qc',
        ),
        migrations.AlterField(
            model_name='productionsampleblend',
            name='mesin',
            field=models.CharField(choices=[('fr15', 'fr15'), ('fr25', 'fr25')], default='', max_length=50),
        ),
    ]
