# Generated by Django 3.0.8 on 2020-09-12 06:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_12sep20'),
        ('production', '0003_auto_12sep20'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangkeluar',
            name='tanggal_dan_jam',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 12, 6, 35, 34, 146500, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='packforminput',
            name='tanggal_dan_jam',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 12, 6, 35, 34, 146500, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='productiondiv',
            name='roasted_material',
        ),
        migrations.AddField(
            model_name='productiondiv',
            name='roasted_material',
            field=models.ManyToManyField(to='products.Roaster'),
        ),
    ]
