# Generated by Django 3.0.8 on 2020-07-28 05:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_pack_form_input_runtime_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackFormInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_dan_jam', models.DateTimeField(default=datetime.datetime(2020, 7, 28, 5, 20, 54, 632399, tzinfo=utc))),
                ('volume', models.DecimalField(decimal_places=2, max_digits=9)),
                ('catatan', models.TextField(default='-', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='komposisibean',
            name='tanggal_pembuatan_komposisi',
            field=models.DateField(default=datetime.date(2020, 7, 28)),
        ),
        migrations.AlterField(
            model_name='productiondiv',
            name='roast_date',
            field=models.DateField(default=datetime.date(2020, 7, 28)),
        ),
        migrations.RenameModel(
            old_name='runtime_stock',
            new_name='RunTimeStock',
        ),
        migrations.DeleteModel(
            name='pack_form_input',
        ),
        migrations.AddField(
            model_name='packforminput',
            name='blend_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.RunTimeStock'),
        ),
        migrations.AddField(
            model_name='packforminput',
            name='jenis_pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.Pack'),
        ),
    ]
