# Generated by Django 3.0.8 on 2020-09-12 13:39

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_12sep20'),
        ('production', '0004_auto_12sep20'),
    ]

    operations = [
        migrations.AddField(
            model_name='productiondiv',
            name='blend_name',
            field=models.ForeignKey(default=1, limit_choices_to={'show_this': True}, on_delete=django.db.models.deletion.PROTECT, to='products.BlendName'),
        ),
        migrations.AlterField(
            model_name='barangkeluar',
            name='tanggal_dan_jam',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 12, 13, 39, 20, 608827, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='packforminput',
            name='tanggal_dan_jam',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 12, 13, 39, 20, 608827, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='productiondiv',
            name='production_date',
            field=models.ForeignKey(limit_choices_to={'production_date': datetime.date(2020, 9, 12)}, on_delete=django.db.models.deletion.CASCADE, to='production.BlendReport'),
        ),
    ]
