# Generated by Django 3.0.8 on 2020-09-12 19:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_12sep20'),
        ('production', '0005_auto_12sep20'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangkeluar',
            name='tanggal_dan_jam',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 12, 19, 41, 12, 733745, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='komposisibean',
            name='tanggal_pembuatan_komposisi',
            field=models.DateField(default=datetime.date(2020, 9, 13)),
        ),
        migrations.AlterField(
            model_name='packforminput',
            name='tanggal_dan_jam',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 12, 19, 41, 12, 733745, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='productiondiv',
            name='production_date',
            field=models.ForeignKey(limit_choices_to={'production_date': datetime.date(2020, 9, 13)}, on_delete=django.db.models.deletion.CASCADE, to='production.BlendReport'),
        ),
        migrations.AlterField(
            model_name='productiondiv',
            name='roast_date',
            field=models.DateField(default=datetime.date(2020, 9, 13)),
        ),
        migrations.AlterField(
            model_name='productiondiv',
            name='roasted_material',
            field=models.ManyToManyField(limit_choices_to=models.Q(next_process=False), to='products.Roaster'),
        ),
    ]
