# Generated by Django 3.0.8 on 2020-07-28 05:34

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_auto_20200728_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='runtimestock',
            name='pack_size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='production.Pack'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='packforminput',
            name='tanggal_dan_jam',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 5, 34, 5, 54255, tzinfo=utc)),
        ),
    ]
