# Generated by Django 3.0.8 on 2020-09-13 07:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_auto_13sep20'),
    ]

    operations = [
        migrations.AddField(
            model_name='productiondiv',
            name='catatan_produksi',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='productiondiv',
            name='catatan_qc',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='barangkeluar',
            name='tanggal_dan_jam',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 13, 7, 2, 37, 956150, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='packforminput',
            name='tanggal_dan_jam',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 13, 7, 2, 37, 956150, tzinfo=utc)),
        ),
    ]
