# Generated by Django 3.0.8 on 2020-07-28 08:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_auto_20200728_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaftarCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_customer', models.CharField(max_length=20)),
                ('no_telp', models.CharField(max_length=20)),
                ('alamat', models.CharField(max_length=30)),
                ('pic', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='packforminput',
            old_name='volume',
            new_name='volume_pack',
        ),
        migrations.AddField(
            model_name='packforminput',
            name='volume_quantity',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='packforminput',
            name='tanggal_dan_jam',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 8, 9, 55, 344211, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='BarangKeluar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_dan_jam', models.DateTimeField(default=datetime.datetime(2020, 7, 28, 8, 9, 55, 344211, tzinfo=utc))),
                ('invoice_number', models.CharField(default='-', max_length=20)),
                ('volume_pack', models.DecimalField(decimal_places=2, max_digits=9)),
                ('volume_quantity', models.DecimalField(decimal_places=2, max_digits=9)),
                ('catatan', models.TextField(default='-', max_length=200)),
                ('blend_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.RunTimeStock')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.DaftarCustomer')),
                ('jenis_pack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.Pack')),
            ],
        ),
    ]
