# Generated by Django 3.0.8 on 2020-09-15 15:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_auto_13sep20'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productiondiv',
            name='blend_name',
        ),
        migrations.RemoveField(
            model_name='productiondiv',
            name='shift',
        ),
        migrations.AddField(
            model_name='blendreport',
            name='blend_name_bulanan',
            field=models.ForeignKey(default=1, limit_choices_to={'show_this': True}, on_delete=django.db.models.deletion.PROTECT, to='products.BlendName'),
        ),
        migrations.AlterField(
            model_name='productiondiv',
            name='roast_date',
            field=models.DateField(default=datetime.date(2020, 9, 15)),
        ),
    ]
