# Generated by Django 3.0.8 on 2020-07-28 08:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_auto_20200728_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangkeluar',
            name='tanggal_dan_jam',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 8, 11, 35, 717708, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='packforminput',
            name='tanggal_dan_jam',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 8, 11, 35, 717708, tzinfo=utc)),
        ),
    ]
