# Generated by Django 3.0.8 on 2020-07-30 03:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_auto_20200728_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barangkeluar',
            options={'verbose_name': 'Barang Keluar', 'verbose_name_plural': 'Barang Keluar'},
        ),
        migrations.AlterModelOptions(
            name='packforminput',
            options={'verbose_name': 'Finish Good Input', 'verbose_name_plural': 'Finish Good Input'},
        ),
        migrations.AlterField(
            model_name='barangkeluar',
            name='tanggal_dan_jam',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 30, 3, 52, 43, 590006, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='blendreport',
            name='blend_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.RunTimeStock'),
        ),
        migrations.AlterField(
            model_name='komposisibean',
            name='tanggal_pembuatan_komposisi',
            field=models.DateField(default=datetime.date(2020, 7, 30)),
        ),
        migrations.AlterField(
            model_name='packforminput',
            name='tanggal_dan_jam',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 30, 3, 52, 43, 590006, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='productiondiv',
            name='roast_date',
            field=models.DateField(default=datetime.date(2020, 7, 30)),
        ),
    ]
