# Generated by Django 3.0.8 on 2020-07-30 04:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_auto_20200730_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangkeluar',
            name='tanggal_dan_jam',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 30, 4, 16, 42, 992760, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='packforminput',
            name='tanggal_dan_jam',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 30, 4, 16, 42, 992760, tzinfo=utc)),
        ),
    ]
