# Generated by Django 3.0.8 on 2020-08-30 04:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreceipe',
            name='created',
            field=models.DateField(default=datetime.date(2020, 8, 30)),
        ),
        migrations.AlterField(
            model_name='qcsamplebean',
            name='cupping_date',
            field=models.DateField(default=datetime.date(2020, 8, 30)),
        ),
    ]
