# Generated by Django 3.0.8 on 2020-08-08 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipe', '0002_auto_20200808_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreceipe',
            name='created',
            field=models.DateField(default=datetime.date(2020, 8, 9)),
        ),
        migrations.AlterField(
            model_name='qcsamplebean',
            name='cupping_date',
            field=models.DateField(default=datetime.date(2020, 8, 9)),
        ),
    ]
