# Generated by Django 3.0.8 on 2020-07-30 03:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipe', '0003_auto_20200728_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreceipe',
            name='created',
            field=models.DateField(default=datetime.date(2020, 7, 30)),
        ),
        migrations.AlterField(
            model_name='qcsamplebean',
            name='cupping_date',
            field=models.DateField(default=datetime.date(2020, 7, 30)),
        ),
    ]
