# Generated by Django 3.0.8 on 2020-07-26 14:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeansCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='-', max_length=10)),
                ('beans_name', models.CharField(max_length=50)),
                ('jenis_kopi', models.CharField(max_length=10)),
                ('variety', models.CharField(max_length=10)),
                ('origin', models.CharField(max_length=10)),
                ('paska_panen', models.CharField(default='-', max_length=20)),
                ('vendor_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BeansGudang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beans_name', models.CharField(help_text='format : beans name + lot_number', max_length=50)),
                ('jenis_kopi', models.CharField(max_length=10)),
                ('variety', models.CharField(max_length=10)),
                ('origin', models.CharField(max_length=10)),
                ('paska_panen', models.CharField(default='-', max_length=20)),
                ('crop_year', models.DateField()),
                ('vendor_name', models.CharField(max_length=50)),
                ('lot_number', models.DateField()),
                ('bag', models.PositiveIntegerField()),
                ('qty_bag', models.PositiveIntegerField()),
                ('initial_stock', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('price_kilo_idr', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('last_update_stock', models.DateTimeField(default=datetime.datetime.now)),
                ('qc_acceptance', models.BooleanField(default=False)),
                ('moisture_check', models.PositiveIntegerField(default=0)),
                ('primary_defect', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('secondary_defect', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('aroma_greenbean', models.CharField(default='-', max_length=100)),
                ('fragrance_score', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('fragrance_intensity', models.CharField(default='-', max_length=100)),
                ('fragrance_notes', models.CharField(default='-', max_length=100)),
                ('flavor_score', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('flavor_intensity', models.CharField(default='-', max_length=100)),
                ('flavor_notes', models.CharField(default='-', max_length=100)),
                ('aftertaste_score', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('aftertaste_notes', models.CharField(default='-', max_length=100)),
                ('acidity_score', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('acidity_intensity', models.CharField(default='-', max_length=100)),
                ('acidity_notes', models.CharField(default='-', max_length=100)),
                ('body_score', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('body_intensity', models.CharField(default='-', max_length=100)),
                ('body_notes', models.CharField(default='-', max_length=100)),
                ('balance_score', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('uniformity_score', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('cleancup_score', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('overal_cup', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('defect', models.CharField(default='-', max_length=100)),
                ('cup_score', models.DecimalField(decimal_places=1, max_digits=3)),
                ('sample_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.BeansCode')),
            ],
            options={
                'verbose_name': 'Bahan Baku',
                'verbose_name_plural': 'Bahan Baku',
            },
        ),
        migrations.CreateModel(
            name='Roaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roast_date', models.DateField(auto_now_add=True)),
                ('mesin', models.CharField(choices=[('froco-15', 'froco-15'), ('froco-25', 'froco-25')], default='', max_length=50)),
                ('shift', models.CharField(choices=[('Pagi', 'Pagi'), ('Siang', 'Siang')], default='', max_length=60)),
                ('process', models.CharField(choices=[('dry', 'dry'), ('wet', 'wet')], default='', max_length=50)),
                ('batch_number', models.PositiveIntegerField(max_length=50)),
                ('beans_color', models.CharField(choices=[('wajar', 'wajar'), ('tidak wajar', 'tidak wajar')], default='', max_length=50)),
                ('density', models.DecimalField(decimal_places=3, default=0, max_digits=19)),
                ('moisture_content', models.DecimalField(decimal_places=1, default=0, max_digits=19)),
                ('raw', models.DecimalField(decimal_places=2, max_digits=19)),
                ('roasted', models.DecimalField(decimal_places=2, max_digits=19)),
                ('roaster_pass_check', models.BooleanField(default=False)),
                ('catatan_roaster', models.CharField(default='-', max_length=100)),
                ('beans_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.BeansGudang')),
            ],
        ),
        migrations.CreateModel(
            name='PengambilanGreenbean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField()),
                ('jumlah_diambil', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mesin', models.CharField(choices=[('froco-15', 'froco-15'), ('froco-25', 'froco-25'), ('non-machine', 'non-machine')], default='-', max_length=50)),
                ('shifts', models.CharField(choices=[('Pagi', 'Pagi'), ('Siang', 'Siang')], default='-', max_length=50)),
                ('pic', models.CharField(default='-', max_length=50)),
                ('keterangan', models.CharField(default='-', max_length=100)),
                ('beans_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.BeansGudang')),
            ],
        ),
    ]
