# Generated by Django 3.0.8 on 2020-08-07 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beanscode',
            options={'verbose_name': 'GB Overview', 'verbose_name_plural': 'GB Overview'},
        ),
    ]
