# Generated by Django 3.0.8 on 2020-07-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beansgudang',
            name='inherited_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
