# Generated by Django 3.0.8 on 2020-07-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200717_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='roaster',
            name='catatan_roaster',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
