# Generated by Django 3.0.8 on 2020-09-06 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200824_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlendName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blend_name', models.CharField(default=0, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RoasterName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roaster_technician', models.CharField(max_length=20)),
                ('created_date', models.DateField()),
                ('telp', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RoastErrorLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('roastcode', models.CharField(default='-', max_length=10)),
                ('machine', models.CharField(choices=[('froco-15', 'froco-15'), ('froco-25', 'froco-25')], default='', max_length=50)),
                ('kronology', models.TextField(default='-', max_length=140)),
                ('resolution', models.TextField(default='-', max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileRoast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField()),
                ('profile_name', models.CharField(max_length=20)),
                ('mesin', models.CharField(choices=[('froco-15', 'froco-15'), ('froco-25', 'froco-25')], default='-', max_length=50)),
                ('weight_lose_min', models.DecimalField(decimal_places=2, help_text='in percent', max_digits=5)),
                ('weight_lose_max', models.DecimalField(decimal_places=2, help_text='in percent', max_digits=5)),
                ('beans_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.BeansGudang')),
            ],
        ),
    ]
