# Generated by Django 3.0.8 on 2020-07-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_beansgudang_limit_in_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beansgudang',
            old_name='qc_acceptance',
            new_name='qc_check',
        ),
        migrations.AlterField(
            model_name='beansgudang',
            name='inherited_stock',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=5),
        ),
    ]
