# Generated by Django 3.0.8 on 2020-09-06 14:15

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_blendname_profileroast_roastername_roasterrorlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='roaster',
            name='blend_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='products.BlendName'),
        ),
        migrations.AddField(
            model_name='roaster',
            name='profile_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='products.ProfileRoast'),
        ),
        migrations.AddField(
            model_name='roaster',
            name='roastcode',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='roaster',
            name='roaster',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='products.RoasterName'),
        ),
        migrations.AddField(
            model_name='roasterrorlogs',
            name='roaster',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='products.RoasterName'),
        ),
    ]
