# Generated by Django 3.0.8 on 2020-09-09 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200906_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beansgudang',
            name='last_update_stock',
        ),
        migrations.AlterField(
            model_name='beansgudang',
            name='moisture_check',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
