# Generated by Django 3.0.8 on 2020-09-09 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200909_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roaster',
            name='profile_name',
        ),
        migrations.DeleteModel(
            name='ProfileRoast',
        ),
    ]
