# Generated by Django 3.0.8 on 2020-09-11 19:10
#DONE UPDATE TO PRODUCTION SERVER 12 sep 2020
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200909_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialForecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField()),
                ('periode_bulan', models.CharField(default='-', help_text='Bulan disertai tahun huruf kapital eg; JANUARY 2020', max_length=30)),
                ('work_days', models.PositiveIntegerField(default=1)),
                ('catatan', models.TextField(default='-', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='OverheadForecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='OverheadItemForecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('nama_item', models.CharField(default='-', max_length=50)),
                ('harga_item', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('jumlah_item', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('total_pengeluaran', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('catatan', models.TextField(default='-', max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='blendname',
            name='created_date',
            field=models.DateField(default=datetime.date(2020, 9, 12)),
        ),
        migrations.AddField(
            model_name='blendname',
            name='monthly_target',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='blendname',
            name='periode',
            field=models.CharField(choices=[('JAN', 'JANUARY'), ('FEB', 'FEBRUARY'), ('MAR', 'MARCH'), ('APR', 'APRIL'), ('MAY', 'MAY'), ('JUN', 'JUNE'), ('JUL', 'JULY'), ('AUG', 'AUGUST'), ('SEP', 'SEPTEMBER'), ('OKT', 'OKTOBER'), ('NOV', 'NOVEMBER'), ('DEC', 'DECEMBER')], default='JAN', max_length=3),
        ),
        migrations.AddField(
            model_name='blendname',
            name='show_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roaster',
            name='minggu',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='roaster',
            name='blend_name',
            field=models.ForeignKey(default=1, limit_choices_to={'show_status': True}, on_delete=django.db.models.deletion.PROTECT, to='products.BlendName'),
        ),
    ]
