# Generated by Django 3.0.8 on 2020-09-11 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='beansgudang',
            name='show_this',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pengambilangreenbean',
            name='blend_name',
            field=models.ForeignKey(default=1, limit_choices_to={'show_this': True}, on_delete=django.db.models.deletion.PROTECT, to='products.BlendName'),
        ),
        migrations.AddField(
            model_name='pengambilangreenbean',
            name='minggu',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='pengambilangreenbean',
            name='beans_name',
            field=models.ForeignKey(limit_choices_to={'show_this': True}, on_delete=django.db.models.deletion.CASCADE, to='products.BeansGudang'),
        ),
        migrations.AlterField(
            model_name='roaster',
            name='minggu',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=1),
        ),
    ]
