# Generated by Django 3.0.8 on 2020-09-12 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='roaster',
            name='next_process',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pengambilangreenbean',
            name='beans_name',
            field=models.ForeignKey(limit_choices_to={'show_this': False}, on_delete=django.db.models.deletion.CASCADE, to='products.BeansGudang'),# ini diganti loh jadi false
        ),
    ]
