# Generated by Django 3.0.8 on 2020-09-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_16sep20'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roaster',
            name='next_process',
            field=models.BooleanField(default=False),
        ),
    ]
