# Generated by Django 3.0.8 on 2020-09-17 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_16sep20'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roaster',
            name='process',
        ),
        migrations.AddField(
            model_name='roaster',
            name='set_number',
            field=models.PositiveIntegerField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='beansgudang',
            name='beans_name',
            field=models.CharField(help_text='GUNAKAN HURUF KAPITAL ! format : BEANS NAME + lot_number', max_length=50),
        ),
        migrations.AlterField(
            model_name='blendname',
            name='created_date',
            field=models.DateField(default=datetime.date(2020, 9, 17)),
        ),
        migrations.AlterField(
            model_name='roaster',
            name='minggu',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', help_text='SERING TERJADI KESALAHAN MOHON DIPERHATIKAN', max_length=1),
        ),
    ]
